python3 perturbation.py --config_path             configs/cifar10                \
                        --exp_name                experiments/cifar10_poison/cifar10_ULEO\
                        --version                 mlp                       \
                        --train_data_type         CIFAR10                       \
                        --noise_shape             50000 3 32 32                  \
                        --epsilon                 8                              \
                        --num_steps               20                             \
                        --step_size               0.8                            \
                        --attack_type             min-min                        \
                        --perturb_type            samplewise                      \
                        --universal_stop_error    0.01 \
                        --GRAYAUG 0